# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8cd9c6b9-4649-43f6-a7b4-5c13a53d02e4";
      fsType = "ext4";
    };

  fileSystems."/mnt/parity1" =
    { device = "/dev/disk/by-uuid/99d68a19-51e1-484a-8ea8-5f02a81ab03f";
      fsType = "ext4";
    };

  fileSystems."/mnt/disk1" =
    { device = "/dev/disk/by-uuid/35e1d0cd-f154-4ef0-aa7a-2cdc266ceb5b";
      fsType = "ext4";
    };

  fileSystems."/mnt/disk2" =
    { device = "/dev/disk/by-uuid/84c18c12-d9fd-4027-8ab2-331ce2ad3b9d";
      fsType = "ext4";
    };

  environment.systemPackages = with pkgs; [
    mergerfs
  ];
  fileSystems."/mnt/storage" =
    { fsType = "fuse.mergerfs";
      device = "/mnt/disk*";
      options = [ "category.create=mspmfs" "minfreespace=50G" "cache.files=off" "dropcacheonclose=true" "fsname=mergerfs"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C725-3D01";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3466f243-77a5-4729-ab1a-d7657bfd3c12"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
